

create database flujo_ITLA
go
use flujo_ITLA
go


CREATE TABLE USUARIO(
ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CODIGO_USUARIO AS ('ID'+RIGHT ('00'+ CONVERT(VARCHAR,ID_USUARIO),(2))),
NOMBRE NVARCHAR(30) NOT NULL,
APELLIDO NVARCHAR(40) NOT NULL,
_USER NVARCHAR(50) NOT NULL UNIQUE,
_PASSWORD NVARCHAR(50) NOT NULL,
ROL NVARCHAR(20) NOT NULL,
FECHANAC DATE NOT NULL
)

Create table VISITANTE(
ID_VISITANTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CODIGO_VISITANTE AS ('VI'+RIGHT ('00'+ CONVERT(VARCHAR,ID_VISITANTE),(2))),
NOMBRE NVARCHAR(30) NOT NULL,
APELLIDO NVARCHAR(40) NOT NULL,
CARRERA NVARCHAR(40) NULL,
CORREO NVARCHAR(40) NULL,
EDIFICIO NVARCHAR(40) NOT NULL,
AULA NVARCHAR(10) NOT NULL,
HORA_ENTRADA DATETIME DEFAULT(GETDATE()),
MOTIVO_VISITA NVARCHAR(256) NULL
)
GO
create table EDIFICIO(
ID_EDIFICIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CODIGO_EDIFICIO AS ('ED'+RIGHT ('00'+ CONVERT(VARCHAR,ID_EDIFICIO),(2))),
NOMBRE NVARCHAR(30) NOT NULL,
NIVEL INT NOT NULL
)
GO
CREATE TABLE AULA(
ID_AULA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CODIGO_AULA AS ('AU'+RIGHT ('00'+ CONVERT(VARCHAR,ID_AULA),(2))),
NOMBRE NVARCHAR(30) NOT NULL,
ID_EDIFICIO int not null references EDIFICIO(ID_EDIFICIO)
)
GO
--INSERT INTO Tbl_Loging VALUES ('DLOPEZ', 'DL1997')
INSERT INTO USUARIO VALUES ('pedro', 'rosario','Prosario', '1234','Administrador' ,'2000-12-13')
INSERT INTO USUARIO VALUES ('daniel', 'lopez','DLOPEZ', 'DL1997', 'Administrador','2000-12-20')

GO
------------------------------------------------------------------------------------------
-----procedimiento login-------
CREATE PROC SP_Loging
@USER VARCHAR(50),
@PASSWORD VARCHAR(50)
AS
SELECT _USER, _PASSWORD, ROL
FROM USUARIO
WHERE _USER = @USER
AND _PASSWORD = @PASSWORD
GO
------PROCEDIMIENTO PARA BUSCAR-----------
go
CREATE PROC SP_buscarUsuario
@BUSCAR NVARCHAR(30)
AS
SELECT * FROM USUARIO
WHERE nombre LIKE @BUSCAR + '%'

------PROCEDIMIENTO INSERTAR PERSONA--------
GO
CREATE PROC SP_InsertarUsuario
@NOMBRE NVARCHAR(30),
@APELLIDO NVARCHAR(40),
@_USER NVARCHAR(50),
@_PASSWORD NVARCHAR(50),
@ROL NVARCHAR(20),
@FECHANAC DATE 
AS
INSERT INTO USUARIO VALUES(@NOMBRE, @APELLIDO, @_USER, @_PASSWORD,@ROL,@FECHANAC)

------PROCEDIMIENTO EDITAR PERSONA------------
GO
CREATE PROC SP_EditarUsuario
@ID_USUARIO INT,
@NOMBRE NVARCHAR(30),
@APELLIDO NVARCHAR(40),
@_USER NVARCHAR(50),
@_PASSWORD NVARCHAR(50),
@ROL NVARCHAR(20),
@FECHANAC DATE 
AS
UPDATE USUARIO SET nombre = @NOMBRE, apellido = @APELLIDO, _USER = @_USER,
 _PASSWORD = @_PASSWORD, ROL = @ROL, FECHANAC = @FECHANAC
WHERE ID_USUARIO = @ID_USUARIO

-------PROCEDIMIENTO ELIMINAR PERSONA---------
GO
CREATE PROC SP_EliminarUsuario
@ID_USUARIO INT 
AS
DELETE USUARIO 
WHERE ID_USUARIO = @ID_USUARIO
go
-------------------------------------------------------------------

------PROCEDIMIENTO PARA BUSCAR-----------
go
CREATE PROC SP_BuscarVisitante
@BUSCAR NVARCHAR(30)
AS
SELECT * FROM VISITANTE
WHERE EDIFICIO LIKE @BUSCAR + '%'

------PROCEDIMIENTO INSERTAR persona--------
GO
CREATE PROC SP_InsertarVisitante
@NOMBRE NVARCHAR(30),
@APELLIDO NVARCHAR(40),
@CARRERA NVARCHAR(40),
@CORREO NVARCHAR(40),
@EDIFICIO NVARCHAR(40),
@AULA NVARCHAR(10),
@HORA_ENTRADA DATETIME, 
@MOTIVO_VISITA NVARCHAR(256)
AS
INSERT INTO VISITANTE VALUES(@NOMBRE, @APELLIDO, @CARRERA, @CORREO,  @EDIFICIO, @AULA, @HORA_ENTRADA, @MOTIVO_VISITA)

------PROCEDIMIENTO EDITAR PERSONA------------
GO
CREATE PROC SP_EditarVisitante
@ID_VISITANTE INT,
@NOMBRE NVARCHAR(30),
@APELLIDO NVARCHAR(40),
@CARRERA NVARCHAR(40),
@CORREO NVARCHAR(40),
@EDIFICIO NVARCHAR(40),
@AULA NVARCHAR(10),
@HORA_ENTRADA DATETIME, 
@MOTIVO_VISITA NVARCHAR(256)
AS
UPDATE VISITANTE SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, CARRERA = @CARRERA, CORREO = @CORREO,@EDIFICIO = @EDIFICIO,
AULA = @AULA, HORA_ENTRADA = @HORA_ENTRADA, MOTIVO_VISITA = @MOTIVO_VISITA
WHERE ID_VISITANTE = @ID_VISITANTE

-------PROCEDIMIENTO ELIMINAR PERSONA---------
GO
CREATE PROC SP_EliminarVisitante
@ID_VISITANTE INT 
AS
DELETE VISITANTE 
WHERE ID_VISITANTE = @ID_VISITANTE
go
----------------------------------------------------------------------------------------------------------------

------PROCEDIMIENTO PARA BUSCAR-----------
go
CREATE PROC SP_BuscarEdificio 
@BUSCAR NVARCHAR(30)
AS
SELECT * FROM EDIFICIO
WHERE NOMBRE LIKE @BUSCAR + '%'

------PROCEDIMIENTO INSERTAR EDIFICIO--------
GO
CREATE PROC SP_InsertarEdificio

@NOMBRE NVARCHAR(30),
@NIVEL INT
AS
INSERT INTO EDIFICIO VALUES(@NOMBRE, @NIVEL)

------PROCEDIMIENTO EDITAR EDIFICIO------------
GO
CREATE PROC SP_EditarEdificio
@ID_EDIFICIO INT,
@NOMBRE NVARCHAR(30),
@NIVEL INT
AS
UPDATE EDIFICIO SET nombre = @NOMBRE, NIVEL = @NIVEL
WHERE ID_EDIFICIO = @ID_EDIFICIO

-------PROCEDIMIENTO ELIMINAR EDIFICIO---------
GO
CREATE PROC SP_EliminarEdificio
@ID_EDIFICIO INT 
AS
DELETE EDIFICIO 
WHERE ID_EDIFICIO = @ID_EDIFICIO
go
---------------------------------------------------

------PROCEDIMIENTO PARA BUSCAR-----------
go
CREATE PROC SP_BuscarAula1
@BUSCAR NVARCHAR(30)
AS
SELECT * FROM AULA
WHERE NOMBRE LIKE @BUSCAR + '%'

------PROCEDIMIENTO INSERTAR AULA--------
GO
CREATE PROC SP_InsertarAula
@NOMBRE NVARCHAR(30),
@ID_EDIFICIO INT
AS
INSERT INTO AULA VALUES(@NOMBRE, @ID_EDIFICIO)

------PROCEDIMIENTO EDITAR AULA------------
GO
CREATE PROC SP_EditarAula
@ID_AULA INT,
@NOMBRE NVARCHAR(30),
@ID_EDIFICIO INT
AS
UPDATE AULA SET nombre = @NOMBRE, iD_EDIFICIO = @ID_EDIFICIO
WHERE ID_AULA = @ID_AULA

-------PROCEDIMIENTO ELIMINAR PERSONA---------
GO
CREATE PROC SP_EliminarAula
@ID_AULA INT 
AS
DELETE AULA 
WHERE ID_AULA = @ID_AULA
go
---------------------------------------------------
CREATE PROC SP_ComboxEdificio
AS
SELECT ID_EDIFICIO ,NOMBRE FROM EDIFICIO
go
CREATE PROC SP_ComboxAula
@ID_EDIFICIO INT 
AS
SELECT ID_EDIFICIO, NOMBRE FROM AULA WHERE ID_EDIFICIO = @ID_EDIFICIO


delete  AULA